name: Publish package to GitHub Packages

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/asdf-cached-install
      - shell: bash
        run: "sed -i '' 's/0.0.0/${{ github.event.release.tag_name }}/g' package.json"
      - shell: bash
        run: cat package.json
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}