name: Create Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: bump-version
        run: |
          ./bump_version.sh
          cat package.json
          "version=(npm pkg get version --workspaces=false | tr -d \")" >> "$GITHUB_OUTPUT"
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bump-version.outputs.version }}
          name: ${{ steps.bump-version.outputs.version }}
          body: ""
          draft: false
          prerelease: false