name: Publish package to GitHub Packages

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/asdf-cached-install
      - shell: bash
        run: |
          GITHUB_RELEASE_TAG="${{ github.event.release.tag_name }}"
          sed -i 's/"version": "0.0.0"/"version": "'"$GITHUB_RELEASE_TAG"'"/g' package.json
          cat package.json
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}