name: Publish package to GitHub Packages

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/asdf-cached-install
      - shell: bash
        run: npm version --no-git-tag-version ${{ github.event.release.tag_name }}
      - shell: bash
        run: cat package.json
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}